backup Wed Jun  7 10:13:54 PM IST 2023

diff --git a/dots b/dots
--- a/dots
+++ b/dots
@@ -24,8 +24,8 @@ error(){
 
 backup(){
   cd $LOCATION
-  ls backups || mkdir backups
 
+  ls backups || mkdir backups
   # copying files
   cat $LOCATION/list.txt | while read line 
   do
@@ -34,6 +34,18 @@ backup(){
     cp -r "$HOME/$line" "backups/$(basename $line)" || error "cannot copy $line"
   done
 
+  mkdir private
+  cat $LOCATION/private.txt | while read line
+  do
+    echo "backing up [private] $line"
+    cp -r "$HOME/$line" "private/$(basename $line)" || error "cannot copy $line"
+  done
+
+  tar -czvf secrets.tar private
+  rm -r private
+  gpg --encrypt --sign --armour -r ayushmantripathy2004@gmail.com secrets.tar
+  rm secrets.tar
+  mv secrets.tar.asc backups/
   push_to_git
 }
 
